### ISSUE TITLE
Expose net.Conn to RequestCtx

### ISSUE THREAD

**Issue by illotum** [erikdubbelboer/fasthttp#1]
First of all, really appreciate work you're doing Erik!

There is a small feature I'm looking to add to fasthttp and it appears your fork is the only sane way of doing it: https://github.com/valyala/fasthttp/issues/286

Would you be interested in merging this change?

**Comment by erikdubbelboer** [comment]
Yes I think that would be a good addition. If you could make a pull request for an Getter method I'll merge it.

**Comment by illotum** [comment]
Thanks!
