### ISSUE TITLE
session management for fasthttp fork

### ISSUE THREAD

**Issue by NexoMichael** [erikdubbelboer/fasthttp#11]
Hi,

Will it be welcome to add session management like from here https://github.com/fasthttp-contrib/sessions to fasthttp fork? Or it is better to make additional repo for session management that could work with this fork?

(The same question about websocket support)

Best

**Comment by thehowl** [comment]
If I were you, I would fork the repo you're looking to use, clone it into `$GOPATH/src/github.com/NexoMichael/[name]`, go in that folder and do a bit of `find`ing and `sed`ding:

```sh
find . -type f -not -path './.git/*' -exec sed -i 's/valyala/erikdubbelboer/g' {} +
find . -type f -not -path './.git/*' -exec sed -i 's/OriginalAuthor/NexoMichael/g' {} +
```

commit and push, and you should be good to go. Optionally add yourself on top of the LICENSE file and put in the README that this works with the fork. This is the approach I followed for my fork of [fasthttprouter](https://github.com/thehowl/fasthttprouter)

**Comment by erikdubbelboer** [comment]
I guess anyone is welcome to fork those projects and change them to `erikdubbelboer/fasthttp`. I'm not using those projects myself so it's best if I don't do it.
