### ISSUE TITLE
whitespace after http chunk-size

### ISSUE THREAD

**Issue by digidis** [erikdubbelboer/fasthttp#34]
There seems to be servers/load balancers that insert one (or more?) whitespaces between the chunk-size number and \r\n. Most clients seems to accept this as I understand it, but fasthttp is more strict and fails. To fix it extra whitespaces needs to be thrown away in parseChunkSize()

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/erikdubbelboer/fasthttp/commit/29cd5a776f5ece5b2b9e5fd74858aa1b63435056

**Comment by digidis** [comment]
Great!
