### ISSUE TITLE
Join Gofrs community?

### ISSUE THREAD

**Issue by illotum** [erikdubbelboer/fasthttp#49]
There's a chance to offload a bit of responsibility by letting volunteers to help with the codebase: https://medium.com/@theckman/keeping-important-go-packages-alive-5242917f83e8

**Comment by erikdubbelboer** [comment]
I'm not sure if that's a good idea. Having extra people to make pull requests is good but I think in the end you need one person to decide on what to approve and what needs to change. One person to lead the vision of the project. If you have an organization where lots of random people have write access you'll get multiple people changing different things making a mess out of it. Gofrs might work but its so young now that I prefer to first see how they are going to manage multiple packages and users.

**Comment by dgrr** [comment]
I agree with @erikdubbelboer but I think we can join this community keeping Erik as unique maintainer. What do you think?

**Comment by erikdubbelboer** [comment]
@dgrr in that case what would be the advantage?

**Comment by illotum** [comment]
Probably @dgrr means we'll have more public visibility and possibly more folks writing PRs to fix issues. There still will be one person accepting them.

**Comment by dgrr** [comment]
Yes, I think we will have more visibility and usage and PRs and issues, etc... But also I want you (@erikdubbelboer ) to be the admin of the fasthttp.

**Comment by erikdubbelboer** [comment]
Gofrs is so new I want to see some more on how it develops first. I'll keep this issue open for now to reconsider it in a month.
