### ISSUE TITLE
Original fasthttp

### ISSUE THREAD

**Issue by savsgio** [erikdubbelboer/fasthttp#51]
Hi @erikdubbelboer,

It seems that @kirillDanshin get again the development of valyala/fasthttp.

But, Will you create an MR with all bugfixes and enhancements that your repository has?

**Comment by dgrr** [comment]
And @erikdubbelboer will become a maintainer of the original fasthttp?

**Comment by erikdubbelboer** [comment]
Yes I guess I will create a pull request for all changes at once. I'm about to fly for the next days so I won't have time for this until Thursday.

I would like to become a maintainer but I'm not sure if @kirillDanshin and @valyala would like this. Or even if @kirillDanshin is ok with it @valyala still has to do this and he hasn't been active for months.

**Comment by kirillDanshin** [comment]
fasthttp has a huge list of russian-language-copmanies which should anyway test every single patch and now I should ping the list members. But, anyway, @valyala said to me that it is possible to add most frequent contributors later. Currently I have only write permissions, not admin

**Comment by erikdubbelboer** [comment]
@kirillDanshin I would be honored to be added as collaborator.

For now, would you like me to do one big pull request with all changes or separate ones for specific features? I think some of the pull requests I have merged in my fork are still open as pull requests on the original.

**Comment by kirillDanshin** [comment]
@erikdubbelboer to get more specific test results I need separated PRs, if you don't mind.

anyway, when I solve opened issues/PRs and test fixes with biggest fasthttp users, I'll talk with @valyala about adding new collaborators.
for now we can use gramework's [telegram chat](https://t.me/gramework) or [discord server](https://discord.gg/HkW8DsD) for collaboration questions

**Comment by kataras** [comment]
These are sad news, @valyala shouldn't put @kirillDanshin as the maintainer. He it is not responsible for this thing, look his last commits and his code. @erikdubbelboer please keep this fork alive.

**Comment by toby3d** [comment]
@kataras Why? He is quite active in the community and produces effective code. He knows how to keep the project up to date.

**Comment by onokonem** [comment]
> These are sad news, @valyala shouldn't put @kirillDanshin as the maintainer.

I would say this is not that bad as it looks like :)

@kirillDanshin is qualified enough to keep this project alive and busy enough to avoid unnecessary changes.

**Comment by YamiOdymel** [comment]
> These are sad news, @valyala shouldn't put @kirillDanshin as the maintainer. He it is not responsible for this thing, look his last commits and his code. @erikdubbelboer please keep this fork alive.

Well... I don't see any problem if @kirillDanshin maintains the project.

He did even taught me a lot about how to truly test a Golang project, and the things he told me is long as like a blog article, I really learned a lot from what he did.
