### ISSUE TITLE
is there any difference between this version vs valyala/fasthttp?

### ISSUE THREAD

**Issue by unisqu** [erikdubbelboer/fasthttp#52]
came across this one from reference of another go software... any major difference?

**Comment by unisqu** [comment]
i came across this one, would u recommend this?
https://github.com/jackwhelpton/fasthttp-routing

**Comment by illotum** [comment]
This fork served as a temporary development base for fasthttp. All maintainers are now concentrating their effort on valyala/fasthttp and this codebase will probably be frozen.

**Comment by erikdubbelboer** [comment]
I created this fork before I became a maintainer of [valyala/fasthttp](https://github.com/valyala/fasthttp). Since then all changes to my fork have been merged into the original so I should probably add a deprecation warning to my fork.
